### PR TITLE
refactor(Effects): Remove runEffects and StateUpdates, add NgModule (#2)

### PR DESCRIPTION
**Pull request by MikeRyanDev**
Take #2. See previous discussion in #32.

Last version had the following issues:
- You couldn't inject bootstrap-dependent services like `Router`. This is because services implementing `OnDestroy` were being created immediately before the root component(s) had been bootstrapped
- Creating the subscription in the constructor of the services made testing difficult
- Services being automatically instantiated if they implement `OnDestroy` is not apparent to developers

This PR introduces an API that is a bit more familiar.

Effects services:

``` ts
import { Injectable } from '@angular/core';
import { Action, Effect } from '@ngrx/effects';

@Injectable()
export class AuthEffects {
  constructor(private actions$: Actions) { }

  @Effect() login$ = this.actions$
    .ofType('login')
    .mergeMap(...)
}
```

Running them:

``` ts
import { EffectsModule } from '@ngrx/effects';

@NgModule({
  imports: [
    ...,
    EffectsModule.run(AuthEffects)
  ]
})
export class AppModule { }
```

For effects that are dependent on a component being bootstrapped there is `EffectsModule.runAfterBootstrap(token)`. For multiple effects, you must call `EffectsModule.run` multiple times.

Modules that you route to dynamically will start effects for you. However, I'm not sure if this is a bug but the `ngOnDestroy` method of routed modules is not being called when the component is destroyed. If you are running effects dynamically this way and want to clean up the subscription when you leave the route you can use the `EffectsSubscription` service:

``` ts
import { EffectsSubscription } from '@ngrx/effects';

@Component({ ... })
export class SomeRoutableComponent {
  constructor(private subscription: EffectsSubscription) { }

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }
}
```

Published as v2.0.0-beta.2. Shouldn't be any breaking changes if you were using v2.0.0-beta.1.

cc @fxck @btroncone @robwormald @meenie @awerlang

### CODE REVIEW

**Comment by DzmitryShylovich** [comment]
> For multiple effects, you must call EffectsModule.run multiple times.

:disappointed:

**Comment by MikeRyanDev** [comment]
@DzmitryShylovich I'll keep iterating until it is good. Hopefully this is a step in the right direction from beta 1.

**Comment by fxck** [comment]
> /@ngrx/effects/module.d.ts:3:22
>     Generic type 'Type<T>' requires 1 type argument(s).

**Comment by brandonroberts** [comment]
`Type` is a generic now, so it will need be updated to `Type<any>`

**Comment by MikeRyanDev** [comment]
Beta 3 has been published

**Comment by nadavsinai** [comment]
Hi @MikeRyan52 and all, I appreciate your work on this awesome library. I am using it today in it's 1.x branch in what would be a large application, currently in early stages, we have 50~ effects running.
I follow the discussion here and on #32 and I am quite worried about how much the API is going to change. I understand the problems with offline compilation and the targets you set to yourselves with regards to automatically running and stopping the effects upon module load, however I still wonder why the statusUpdates was dropped and now we need to refactor to use actions only observable (see also #44 ) also causing the change of .whenAction to .ofType (yet more app-wide refactoring)... 
also, until we get 2.x solid, can we have a 1.x release compatible with rc6 ? would you like me to have a go at it with a PR?
Thanks,
Nadav Sinai

**Comment by combmag-zz** [comment]
@MikeRyan52 is there any example on how to mock a state for unit testing an effect?

**Comment by brandonroberts** [comment]
This may not affect whether `runAfterBootstrap` exists or not, but services needing the router won't need to use it in `2.1.0`. This PR removes the check that causes the error to be thrown https://github.com/angular/angular/pull/11656

**Pull request merged**
