### PR TITLE
Fixed @angular/core perDependency

### PR DESCRIPTION
**Pull request by vitaliy-bobrov**

### CODE REVIEW

**Comment by nghiado** [comment]
Can someone review and merge this PR? 
We're trying to get rid of warning with Angular4
npm WARN @ngrx/effects@2.0.2 requires a peer of @angular/core@^2.0.0 but none was installed.

**Comment by karolmie1** [comment]
You can fork, and merge this pull request on your own (Just as I did). Unfortunately it may take a really long time for this to be merged.

**Comment by vitaliy-bobrov** [comment]
But it should be published to npm. Is this project still maintained?

**Comment by karolmie1** [comment]
@vitaliy-bobrov That was just a quick tip for ngihiando, of course it should be merged. The more publicity, the quicker it will be I guess.

**Comment by nghiado** [comment]
@karolmie1 Thanks for your tip. Yes I can do it but it's such a small change and many issues were opened related to this so I think the maintainer should consider fixing it asap.
More bugs related to this
https://github.com/ngrx/effects/issues/130
https://github.com/ngrx/effects/issues/120

**Comment by tobiasmuecksch** [comment]
Who is responsible for merging pull requests?

**Comment by pfrendo** [comment]
@MikeRyanDev

**Comment by kylecordes** [comment]
(FYI - I think all of the folks responsible for looking at this, merging, publishing, are quite busy this week at ng-conf. Major conferences tend to occupy the participants 24/7 for the duration. It might be realistic to hope for an update next week when most people are back at their workplace.)

**Comment by tobiasmuecksch** [comment]
Thank you for the information @kylecordes

**Comment by davefedele** [comment]
It might be best to modify the syntax a bit to:
```
 "@angular/core": "^2.0.0 || ^4.0.0",
```

On another note, this is preventing shrinkwrap from working because of the dependency errors.

Thanks!

**Comment by karolmie1** [comment]
I hope they survived the conference. Shame noone looks over this lonely piece of tech I recklesly decided to use in my project 😢

**Comment by fxck** [comment]
Wow, don't be such a cry baby. This was already fixed in 2.0.3 release #142, not to mention they are quite hard at work migrating and updating everything at the [platform](https://github.com/ngrx/platform/commits/master) repo.

**Comment by karolmie1** [comment]
I can't help it, it's a medical condition. Good to know about this platform thing, I was just afraid the project is dead. I'll be watching!

**Comment by brandonroberts** [comment]
Fixed in #142

**Pull request closed without merging**
